language: c

addons:
  apt:
    packages:
      - python3-dev
      - libiberty-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi

script:
  - ./autogen.sh
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./configure; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./configure --without-libiberty; fi
  - make
  - make check

matrix:
  allow_failures:
    - compiler: clang
  include:
  - os: linux
    compiler: gcc
    dist: trusty
  - os: linux
    compiler: clang
    dist: trusty
  - os: osx
    compiler: gcc
    osx_image: xcode8.2
  - os: osx
    osx_image: xcode8.2
    compiler: clang
  - os: osx
    osx_image: xcode8.3
    compiler: clang
  - os: osx
    osx_image: xcode9
    compiler: clang
